[config]

[templates.hyprland]
input_path = "~/.config/matugen/templates/hyprland.conf"
output_path = "~/.config/hypr/colors.conf"

[templates.ghostty]
input_path = "~/.config/matugen/templates/ghostty"
output_path = "~/.cache/matugen/ghostty-colors"

[templates.waybar]
input_path = "~/.config/matugen/templates/waybar.css"
output_path = '~/.config/waybar/colors.css'
# post_hook = 'pkill -SIGUSR2 waybar'

[templates.rofi]
input_path = "~/.config/matugen/templates/rofi.rasi"
output_path = "~/.config/rofi/colors.rasi"

[templates.quickshell]
input_path = "~/.config/matugen/templates/quickshell-colors.qml"
output_path = "~/.config/quickshell/theme/Theme.qml"
