// Generated by matugen
pragma Singleton
import QtQuick

QtObject {
    property color bg: "#0f1417"
    property color fg: "#dfe3e7"
    property color accent: "#92cef5"
    property color dim: "#004c6b"
    property color secondary: "#b6c9d8"
    property color secondaryDim: "#374955"
    property color colTertiary: "#ccc1e9"
    property color colMuted: "#8b9198"
    property color colError: "#ffb4ab"
    property color colSurfaceVariant: "#41484d"
    property color colShadow: "#000000"
}
