-- Generated by matugen
return {
	bg = "{{ colors.surface.default.hex }}",
	bg_dark = "{{ colors.surface_dim.default.hex }}",
	bg_float = "{{ colors.surface.default.hex }}",
	bg_popup = "{{ colors.surface.default.hex }}",
	bg_visual = "{{ colors.surface_variant.default.hex }}",

	fg = "{{ colors.on_surface.default.hex }}",
	fg_dark = "{{ colors.on_surface_variant.default.hex }}",
	fg_gutter = "{{ colors.surface_variant.default.hex }}",
	comment = "{{ colors.outline.default.hex }}",

	border = "{{ colors.outline.default.hex }}",

	red = "{{ colors.error.default.hex }}",
	green = "{{ colors.tertiary.default.hex }}",
	yellow = "{{ colors.secondary.default.hex }}",
	blue = "{{ colors.primary.default.hex }}",
	magenta = "{{ colors.secondary_container.default.hex }}",
	cyan = "{{ colors.tertiary_container.default.hex }}",

	red1 = "{{ colors.error_container.default.hex }}",
	green1 = "{{ colors.tertiary_fixed.default.hex }}",
	green2 = "{{ colors.tertiary_fixed.default.hex }}",
	orange = "{{ colors.secondary_fixed_dim.default.hex }}",
	blue0 = "{{ colors.primary_fixed.default.hex }}",
	blue1 = "{{ colors.primary_fixed.default.hex }}",
	blue2 = "{{ colors.primary_fixed.default.hex }}",
	blue5 = "{{ colors.primary.default.hex }}",
	blue6 = "{{ colors.tertiary_fixed.default.hex }}",
	blue7 = "{{ colors.surface_dim.default.hex }}",
	magenta2 = "{{ colors.secondary_fixed.default.hex }}",
	purple = "{{ colors.secondary_fixed.default.hex }}",
	teal = "{{ colors.tertiary_fixed.default.hex }}",

	selection = "{{ colors.surface_variant.default.hex }}",
	accent = "{{ colors.primary.default.hex }}",
	accent_muted = "{{ colors.primary_container.default.hex }}",
	cursorline = "{{ colors.surface_dim.default.hex }}",
	shadow = "{{ colors.shadow.default.hex }}",
}
