// Generated by matugen
pragma Singleton
import QtQuick

QtObject {
    property color bg: "{{ colors.surface.default.hex }}"
    property color fg: "{{ colors.on_surface.default.hex }}"
    property color accent: "{{ colors.primary.default.hex }}"
    property color dim: "{{ colors.primary_container.default.hex }}"
    property color secondary: "{{ colors.secondary.default.hex }}"
    property color secondaryDim: "{{ colors.secondary_container.default.hex }}"
    property color colTertiary: "{{ colors.tertiary.default.hex }}"
    property color colMuted: "{{ colors.outline.default.hex }}"
    property color colError: "{{ colors.error.default.hex }}"
    property color colSurfaceVariant: "{{ colors.surface_variant.default.hex }}"
    property color colShadow: "{{ colors.shadow.default.hex }}"
}
